// ============================================================
// VeriDoc AI — Shared TypeScript Interfaces (authoritative)
// PART 7 — All fields mandatory. No field may be renamed.
// ============================================================

export interface ValidationResult {
  id: string;
  // Format: "cert-{Date.now()}-{index}"

  fileName: string;

  forgeryScore: number;
  // Range: 0-100, MUST be computed — NEVER Math.random()

  status: 'authentic' | 'suspicious' | 'fake';
  // authentic:  forgeryScore >= 85
  // suspicious: forgeryScore >= 50 and < 85
  // fake:       forgeryScore < 50

  shapeAnalysis: {
    layoutScore: number;
    sealPosition: string;
    textAlignment: string;
    logoIntegrity: string;
  };

  morphHash: string;
  // "0x" + exactly 16 hex chars — derived from 8x8 pixel sampling

  suspiciousZones: Array<{
    area: string;
    confidence: number;
    reason: string;
    bbox?: { x: number; y: number; width: number; height: number };
  }>;

  metadata: {
    institution: string;
    issueDate: string;
    certificateType: string;
    verificationMethod: 'Local Database' | 'Institution API';
    language: string;
  };

  ocrText: string;
  ocrWords: Array<{
    text: string;
    bbox: { x0: number; y0: number; x1: number; y1: number };
    suspicious: boolean;
  }>;

  qrData: string;
  timestamp: string;

  explanations: Array<{
    type:
      | 'font_mismatch'
      | 'layout_anomaly'
      | 'image_tampering'
      | 'text_inconsistency'
      | 'suspicious_keyword'
      | 'seal_missing';
    description: string;
    severity: 'high' | 'medium' | 'low';
    linkedZoneIndex?: number;
  }>;

  ela?: string;

  // Forensic text analysis result
  forensicAnalysis?: {
    authenticity_score: number;
    tampering_risk: 'low' | 'medium' | 'high';
    ai_generated_likelihood: 'low' | 'medium' | 'high';
    verdict: 'Likely Authentic' | 'Suspicious - Requires Review' | 'Likely Forged';
    key_reasons: string[];
    flagged_passages: string[];
  };

  // Compliance validation result
  complianceResult?: {
    overall_compliance_score: number;
    aligned_percentage: number;
    violations: Array<{ violating_statement: string; reference_rule: string }>;
    missing_requirements: string[];
  };
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  source?: 'groq' | 'tavily' | 'deepseek' | 'pdf';
  sources?: Array<{ url: string; title: string }>;
}

export interface AppState {
  validationResults: ValidationResult[];
  isValidating: boolean;
  offlineMode: boolean;
  theme: 'light' | 'dark';
  concurrency: number; // 1-4, default 3
  selectedLanguage: string; // 'auto'|'eng'|'tam'|'hin'|'ben'|'mar'|'guj'|'urd'|'kan'|'mal'
  activeResultId: string | null;
  highlightedZoneIndex: number | null;
  highlightedExplanationIndex: number | null;

  // Chat & LLM state
  chatHistory: ChatMessage[];
  activeModel: 'llama3-70b-8192' | 'mixtral-8x7b-32768' | 'deepseek-chat';
  isSearching: boolean; // true while Tavily search is in progress
  isChatLoading: boolean;
  suggestedQuestions: string[]; // Generated by Groq after PDF upload
  pdfUrl: string | null; // URL.createObjectURL result for mini player
  isMiniPlayerOpen: boolean;
  isMiniPlayerMinimized: boolean;
  pdfExtractedText: string; // Full text extracted from PDF for Groq
}

export interface Actions {
  prependResult: (r: ValidationResult) => void;
  setValidating: (v: boolean) => void;
  toggleOffline: () => void;
  toggleTheme: () => void;
  setConcurrency: (n: number) => void;
  setLanguage: (lang: string) => void;
  setActiveResult: (id: string | null) => void;
  setHighlightedZone: (i: number | null) => void;
  setHighlightedExplanation: (i: number | null) => void;
  markAsFake: (id: string) => void;
  retryResult: (id: string, newResult: ValidationResult) => void;
  clearAll: () => void;

  // Chat actions
  appendChatMessage: (msg: ChatMessage) => void;
  clearChat: () => void;
  setActiveModel: (model: 'llama3-70b-8192' | 'mixtral-8x7b-32768' | 'deepseek-chat') => void;
  setSearching: (v: boolean) => void;
  setChatLoading: (v: boolean) => void;
  setSuggestedQuestions: (qs: string[]) => void;
  setPdfUrl: (url: string | null) => void;
  setPdfExtractedText: (text: string) => void;
  openMiniPlayer: () => void;
  closeMiniPlayer: () => void;
  toggleMiniPlayerMinimize: () => void;
}
